export type Product = {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: string;
  rating: number;
  storeId: string;
  storeName: string;
  distance: number; // km
  deliveryHours: number;
  description: string;
  tags?: string[];
  imagePrompt?: string;
  stock?: number;
  featured?: boolean;
  trending?: boolean;
};

export type Store = {
  id: string;
  name: string;
  banner: string;
  logo: string;
  rating: number;
  distance: number;
  category: string;
  trusted?: boolean;
  description: string;
};

export const categories = [
  { id: "groceries", name: "Groceries", emoji: "🥦" },
  { id: "electronics", name: "Electronics", emoji: "🎧" },
  { id: "fashion", name: "Fashion", emoji: "👗" },
  { id: "beauty", name: "Beauty", emoji: "💄" },
  { id: "home", name: "Home & Living", emoji: "🪴" },
  { id: "sports", name: "Sports", emoji: "🏏" },
  { id: "books", name: "Books", emoji: "📚" },
  { id: "toys", name: "Toys & Games", emoji: "🧸" },
];

export const stores: Store[] = [
  { id: "s1", name: "Green Basket Mart", banner: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&q=80", logo: "🥬", rating: 4.8, distance: 1.2, category: "groceries", trusted: true, description: "Fresh produce from local farms, delivered in under 2 hours." },
  { id: "s2", name: "Volt Electronics", banner: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=1200&q=80", logo: "⚡", rating: 4.6, distance: 2.1, category: "electronics", trusted: true, description: "Latest gadgets with same-day delivery from your neighborhood store." },
  { id: "s3", name: "Threadwood Studio", banner: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1200&q=80", logo: "👕", rating: 4.7, distance: 3.4, category: "fashion", description: "Curated streetwear and timeless basics, locally crafted." },
  { id: "s4", name: "Bloom & Bath", banner: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=1200&q=80", logo: "🌸", rating: 4.9, distance: 0.8, category: "beauty", trusted: true, description: "Clean beauty essentials from independent makers nearby." },
  { id: "s5", name: "Hearth & Home", banner: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=1200&q=80", logo: "🪴", rating: 4.5, distance: 4.0, category: "home", description: "Plants, decor and small-batch homegoods." },
];

// Helper to generate clean, high-resolution Unsplash product photography links
const img = (photoId: string) => `https://images.unsplash.com/${photoId}?w=800&q=80&auto=format&fit=crop`;

export const products: Product[] = [
  /* ═══════════════ ELECTRONICS (15) ═══════════════ */
  {
    id: "elec-1",
    name: "Wireless ANC Headphones",
    price: 8499,
    originalPrice: 11999,
    image: img("photo-1505740420928-5e560c06d30e"),
    category: "electronics",
    rating: 4.8,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 2,
    stock: 25,
    featured: true,
    trending: true,
    tags: ["Bestseller", "Wireless", "Audio"],
    description: "Premium over-ear headphones with adaptive noise cancellation, 40-hour battery life, and high-fidelity sound.",
    imagePrompt: "A premium wireless noise-cancelling headphone in matte black, floating centered on a pure white studio background, soft natural shadows, professional commercial product photography, 8k resolution, minimalist style"
  },
  {
    id: "elec-2",
    name: "Minimalist Smartwatch",
    price: 6999,
    originalPrice: 8999,
    image: img("photo-1523275335684-37898b6baf30"),
    category: "electronics",
    rating: 4.6,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 2,
    stock: 40,
    featured: true,
    trending: true,
    tags: ["New", "Wearable", "Tech"],
    description: "Sleek fitness smartwatch featuring a crystal-clear AMOLED display, 24/7 heart rate monitoring, and 14-day battery life.",
    imagePrompt: "Premium minimalist smartwatch with charcoal gray band, active tracking screen, centered on light gray gradient background, soft shadow, luxury tech product photography"
  },
  {
    id: "elec-3",
    name: "Ergonomic Gaming Mouse",
    price: 3499,
    originalPrice: 4999,
    image: img("photo-1615663245857-ac93bb7c39e7"),
    category: "electronics",
    rating: 4.7,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 3,
    stock: 18,
    featured: false,
    trending: true,
    tags: ["Gaming", "Accessories"],
    description: "High-precision wireless gaming mouse with 26K DPI optical sensor, customizable RGB lighting, and ultra-lightweight design.",
    imagePrompt: "An ergonomic wireless gaming mouse in matte black, colorful neon RGB highlights under the scroll wheel, isolated on solid light gray background, premium studio lighting"
  },
  {
    id: "elec-4",
    name: "Portable Bluetooth Speaker",
    price: 4599,
    originalPrice: 5999,
    image: img("photo-1608043152269-423dbba4e7e1"),
    category: "electronics",
    rating: 4.5,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 2,
    stock: 30,
    featured: false,
    trending: false,
    tags: ["Portable", "Audio"],
    description: "Rugged waterproof portable Bluetooth speaker with deep bass, 360-degree high-fidelity audio, and up to 20 hours of playtime.",
    imagePrompt: "Rugged cylindrical waterproof bluetooth speaker in forest green, standing upright, clean studio white background with soft reflections"
  },
  {
    id: "elec-5",
    name: "Pro DSLR Camera",
    price: 54999,
    originalPrice: 62999,
    image: img("photo-1516035069371-29a1b244cc32"),
    category: "electronics",
    rating: 4.9,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 4,
    stock: 8,
    featured: true,
    trending: false,
    tags: ["Photography", "Premium"],
    description: "High-performance digital SLR camera featuring a 24.2 MP CMOS sensor, 4K video recording capability, and active autofocus.",
    imagePrompt: "Professional DSLR camera with premium 50mm prime lens attached, set centered on solid pure white photography background, soft commercial lighting"
  },
  {
    id: "elec-6",
    name: "Mechanical Keyboard",
    price: 5499,
    originalPrice: 6999,
    image: img("photo-1587829741301-dc798b83add3"),
    category: "electronics",
    rating: 4.8,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 2,
    stock: 15,
    featured: false,
    trending: true,
    tags: ["Hot", "Accessories"],
    description: "Hot-swappable tactile mechanical keyboard with premium linear switches, sound dampening pads, and durable PBT keycaps.",
    imagePrompt: "A sleek custom mechanical keyboard with white and gray keycaps, compact 75% layout, resting centered on clear pastel studio background"
  },
  {
    id: "elec-7",
    name: "Slim Ultrawide Monitor",
    price: 24999,
    originalPrice: 29999,
    image: img("photo-1527443224154-c4a3942d3acf"),
    category: "electronics",
    rating: 4.7,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 4,
    stock: 6,
    featured: true,
    trending: false,
    tags: ["Workstation", "Display"],
    description: "34-inch curved ultrawide gaming and productivity monitor with HDR400, 144Hz refresh rate, and 99% sRGB color coverage.",
    imagePrompt: "A sleek 34-inch curved ultrawide desktop monitor with thin bezels, showing beautiful minimal wallpaper, centered on absolute white studio background"
  },
  {
    id: "elec-8",
    name: "Ultra Slim Laptop",
    price: 68999,
    originalPrice: 74999,
    image: img("photo-1593642632823-8f785ba67e45"),
    category: "electronics",
    rating: 4.8,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 3,
    stock: 12,
    featured: true,
    trending: true,
    tags: ["Premium", "PC"],
    description: "Thin and lightweight aluminum laptop equipped with an Intel i7 processor, 16GB RAM, and 512GB ultra-fast PCIe SSD storage.",
    imagePrompt: "Modern thin silver aluminum laptop slightly opened, showing sleek operating system interface, on clean white studio backdrop, soft lighting"
  },
  {
    id: "elec-9",
    name: "Quadcopter Drone Camera",
    price: 45999,
    originalPrice: 51999,
    image: img("photo-1473968512647-3e447244af8f"),
    category: "electronics",
    rating: 4.9,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 3,
    stock: 5,
    featured: true,
    trending: true,
    tags: ["Drone", "New"],
    description: "Ultra-lightweight folding drone with 4K HDR camera gimbal, 3-axis stabilizer, 31 minutes flight time, and active obstacle sensing.",
    imagePrompt: "Folding professional quadcopter drone in gray alloy, props unfolded, hovering on pure white background, studio catalog render, realistic shadows"
  },
  {
    id: "elec-10",
    name: "VR Gaming Headset",
    price: 36999,
    originalPrice: 42999,
    image: img("photo-1593508512255-86ab42a8e620"),
    category: "electronics",
    rating: 4.6,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 2,
    stock: 10,
    featured: false,
    trending: true,
    tags: ["VR", "Gaming"],
    description: "All-in-one standalone virtual reality headset with stunning 120Hz high-definition resolution display and 3D spatial audio.",
    imagePrompt: "Sleek white virtual reality VR headset with dual controllers, centered on clean studio light gray background, soft lighting"
  },
  {
    id: "elec-11",
    name: "Fast Charging Power Bank",
    price: 1999,
    originalPrice: 2999,
    image: img("photo-1609081219090-a6d81d3085bf"),
    category: "electronics",
    rating: 4.4,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 2,
    stock: 50,
    featured: false,
    trending: false,
    tags: ["Accessories", "Battery"],
    description: "High-capacity 20,000mAh power bank supporting 22.5W USB-C dual-direction fast charging and intelligent status display.",
    imagePrompt: "Minimalist black rectangle power bank charger, matte texture, with sleek metallic USB-C ports visible, on white studio backdrop"
  },
  {
    id: "elec-12",
    name: "ANC Wireless Earbuds",
    price: 4999,
    originalPrice: 7999,
    image: img("photo-1590658268037-6bf12165a8df"),
    category: "electronics",
    rating: 4.5,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 2,
    stock: 35,
    featured: false,
    trending: true,
    tags: ["Audio", "Wireless"],
    description: "True wireless smart earbuds featuring active noise cancellation, custom deep-bass drivers, and ipx5 sweatproof rating.",
    imagePrompt: "True wireless elegant white earbuds resting outside their compact oval charging case, centered on smooth soft gray gradient backdrop"
  },
  {
    id: "elec-13",
    name: "HD Graphic Tablet",
    price: 7499,
    originalPrice: 9999,
    image: img("photo-1527689368864-3a821dbccc34"),
    category: "electronics",
    rating: 4.7,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 3,
    stock: 14,
    featured: false,
    trending: false,
    tags: ["Design", "Draw"],
    description: "Professional drawing digital tablet with 8192 levels of pressure sensitivity, wireless stylus pen, and customizable hotkeys.",
    imagePrompt: "Digital drawing graphics tablet in charcoal grey, with active black screen and battery-free digital pen resting on top, on white backdrop"
  },
  {
    id: "elec-14",
    name: "5G Smart Television",
    price: 34999,
    originalPrice: 42999,
    image: img("photo-1593305841991-05c297ba4575"),
    category: "electronics",
    rating: 4.7,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 4,
    stock: 7,
    featured: true,
    trending: false,
    tags: ["TV", "Entertainment"],
    description: "43-inch Ultra HD Smart LED TV featuring built-in voice assistant, Dolby Digital surround audio, and streaming platform support.",
    imagePrompt: "Ultra thin 43-inch flat screen TV showing colorful abstract artwork, hanging centered on pure white studio background, studio lighting"
  },
  {
    id: "elec-15",
    name: "Dual-Port Fast Wall Charger",
    price: 1299,
    originalPrice: 1999,
    image: img("photo-1583863788434-e58a36330cf0"),
    category: "electronics",
    rating: 4.5,
    storeId: "s2",
    storeName: "Volt Electronics",
    distance: 2.1,
    deliveryHours: 2,
    stock: 60,
    featured: false,
    trending: false,
    tags: ["Accessories", "Charger"],
    description: "Ultra-compact 33W GaN wall charger supporting dual USB-C and USB-A output ports with advanced thermal protection.",
    imagePrompt: "Mini white dual-port GaN wall charging adapter with folding plugs, centered on clear background, realistic shadows"
  },

  /* ═══════════════ FASHION (15) ═══════════════ */
  {
    id: "fash-1",
    name: "Oversized Cotton Hoodie",
    price: 1999,
    originalPrice: 2999,
    image: img("photo-1556821840-3a63f95609a7"),
    category: "fashion",
    rating: 4.5,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 22,
    featured: true,
    trending: true,
    tags: ["Cozy", "Streetwear"],
    description: "Heavyweight organic cotton loopback fleece hoodie with a relaxed oversized silhouette and high-density stitching.",
    imagePrompt: "Oversized heavy cotton drop-shoulder hoodie in minimalist beige sand color, clean white catalog photography background, soft shadows"
  },
  {
    id: "fash-2",
    name: "Vintage Denim Jacket",
    price: 2899,
    originalPrice: 3999,
    image: img("photo-1576995853123-5a10305d93c0"),
    category: "fashion",
    rating: 4.7,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 15,
    featured: true,
    trending: true,
    tags: ["Vintage", "Outerwear"],
    description: "Classic trucker-style denim jacket crafted from rigid indigo washed denim with durable metal shank buttons.",
    imagePrompt: "Vintage distressed blue denim jacket with classic collar, centered on neutral studio backdrop, high-end apparel catalog style"
  },
  {
    id: "fash-3",
    name: "Premium Designer Sneakers",
    price: 4999,
    originalPrice: 7999,
    image: img("photo-1542291026-7eec264c27ff"),
    category: "fashion",
    rating: 4.8,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 18,
    featured: true,
    trending: true,
    tags: ["Bestseller", "Footwear"],
    description: "Modern designer streetwear running sneaker in white and bright blue accents, side view, floating centered on clean white background.",
    imagePrompt: "Modern designer streetwear running sneaker in white and bright blue accents, side view, floating centered on clean white background, soft shadow, commercial catalog photography style"
  },
  {
    id: "fash-4",
    name: "Relaxed Utility Cargo Pants",
    price: 2499,
    originalPrice: 3499,
    image: img("photo-1594633312681-425c7b97ccd1"),
    category: "fashion",
    rating: 4.4,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 25,
    featured: false,
    trending: true,
    tags: ["Utility", "Comfort"],
    description: "Multi-pocket cargo pants built from sturdy cotton ripstop fabric featuring adjustable ankle cuffs and an elastic waistband.",
    imagePrompt: "Multi-pocket durable cotton utility cargo pants in tactical olive green, laid flat on pure white apparel photography backdrop"
  },
  {
    id: "fash-5",
    name: "Minimalist Gold Accent Watch",
    price: 3899,
    originalPrice: 5499,
    image: img("photo-1524805444758-089113d48a6d"),
    category: "fashion",
    rating: 4.7,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 12,
    featured: true,
    trending: false,
    tags: ["New", "Accessory"],
    description: "Ultra-thin analog dress watch featuring a brushed gold casing, minimalist dial index, and clean black leather strap.",
    imagePrompt: "Minimalist analog watch with round rose gold casing, clean white dial, black Italian leather strap, isolated on neutral studio white background"
  },
  {
    id: "fash-6",
    name: "Polarized Retro Sunglasses",
    price: 1499,
    originalPrice: 2299,
    image: img("photo-1511499767150-a48a237f0083"),
    category: "fashion",
    rating: 4.5,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 30,
    featured: false,
    trending: true,
    tags: ["Polarized", "Retro"],
    description: "Classic acetate frame polarized sunglasses offering 100% UV400 protection and scratch-resistant amber gradient lenses.",
    imagePrompt: "Retro dark acetate tortoise-shell frame sunglasses, amber polarized lenses, resting angled on a soft beige reflective studio surface"
  },
  {
    id: "fash-7",
    name: "Classic Suede Leather Handbag",
    price: 3599,
    originalPrice: 4999,
    image: img("photo-1584917865442-de89df76afd3"),
    category: "fashion",
    rating: 4.6,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 10,
    featured: false,
    trending: false,
    tags: ["Leather", "Bags"],
    description: "Timeless tote bag crafted from premium split suede leather, featuring dual top-handles and a spacious microfiber-lined interior.",
    imagePrompt: "Tan brown premium suede leather structured tote handbag, dual leather handles, centered on studio cream white background, soft shadow"
  },
  {
    id: "fash-8",
    name: "Graphic Streetwear Tee",
    price: 999,
    originalPrice: 1499,
    image: img("photo-1521572267360-ee0c2909d518"),
    category: "fashion",
    rating: 4.4,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 45,
    featured: false,
    trending: true,
    tags: ["Graphic", "Cotton"],
    description: "Relaxed fit crewneck t-shirt made from heavy 240GSM cotton, featuring a high-density colorful typographic chest print.",
    imagePrompt: "Minimal white heavy cotton crewneck t-shirt, small modern abstract graphic print on chest, flat lay on white studio photography background"
  },
  {
    id: "fash-9",
    name: "Casual Linen Shirt",
    price: 1899,
    originalPrice: 2499,
    image: img("photo-1596755094514-f87e34085b2c"),
    category: "fashion",
    rating: 4.6,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 20,
    featured: false,
    trending: false,
    tags: ["Linen", "Breathable"],
    description: "Breathable European flax linen shirt featuring a refined button-down collar and vintage garment-dyed textured finish.",
    imagePrompt: "Pale blue short-sleeve organic linen button-down shirt, ironed clean, flat lay on studio light background"
  },
  {
    id: "fash-10",
    name: "Classic Dad Baseball Cap",
    price: 799,
    originalPrice: 1199,
    image: img("photo-1588850561407-ed78c282e89b"),
    category: "fashion",
    rating: 4.3,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 40,
    featured: false,
    trending: false,
    tags: ["Accessories", "Hats"],
    description: "Unstructured 6-panel cotton twill cap featuring an adjustable brass buckle strap and elegant minimal front embroidery.",
    imagePrompt: "Unstructured washed navy blue cotton dad cap, minimal embroidery logo, centered on clean white backdrop, professional studio display"
  },
  {
    id: "fash-11",
    name: "Summer Floral Dress",
    price: 2199,
    originalPrice: 2999,
    image: img("photo-1595777457583-95e059d581b8"),
    category: "fashion",
    rating: 4.5,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 14,
    featured: false,
    trending: false,
    tags: ["Dresses", "Summer"],
    description: "Lightweight tiered midi dress made from soft organic viscose, decorated with a hand-painted wildflower print.",
    imagePrompt: "Flowy white midi length summer dress with delicate floral prints, hanging from a natural wooden hanger against plain white studio wall"
  },
  {
    id: "fash-12",
    name: "Knit Wool Winter Coat",
    price: 4999,
    originalPrice: 6999,
    image: img("photo-1539571696357-5a69c17a67c6"),
    category: "fashion",
    rating: 4.8,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 8,
    featured: true,
    trending: false,
    tags: ["Premium", "Winter"],
    description: "Double-breasted long winter overcoat crafted from an insulating merino wool blend with premium horn-button detailing.",
    imagePrompt: "Long structured double-breasted overcoat in camel wool brown, centered on high-end apparel catalog white background, soft shadow"
  },
  {
    id: "fash-13",
    name: "Italian Leather Formal Shoes",
    price: 3499,
    originalPrice: 4999,
    image: img("photo-1533867617858-e7b97e060509"),
    category: "fashion",
    rating: 4.7,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 11,
    featured: false,
    trending: false,
    tags: ["Formal", "Premium"],
    description: "Handcrafted Italian calfskin leather Oxford dress shoes featuring a sleek polished finish and durable blake-stitched leather soles.",
    imagePrompt: "Polished dark brown leather Oxford formal dress shoes, side-by-side display, isolated on plain white photography background"
  },
  {
    id: "fash-14",
    name: "Thermal Activewear Hoodie",
    price: 1799,
    originalPrice: 2499,
    image: img("photo-1515886657613-9f3515b0c78f"),
    category: "fashion",
    rating: 4.5,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 19,
    featured: false,
    trending: false,
    tags: ["Athletic", "Activewear"],
    description: "Sweat-wicking technical activewear athletic hoodie with 4-way stretch, secure zip pockets, and thumbnail-grip sleeves.",
    imagePrompt: "Athletic fitted thermal zip hoodie in space gray tech fleece, flat lay on white studio catalog background"
  },
  {
    id: "fash-15",
    name: "Sterling Silver Band Ring",
    price: 899,
    originalPrice: 1299,
    image: img("photo-1605100804763-247f67b3557e"),
    category: "fashion",
    rating: 4.6,
    storeId: "s3",
    storeName: "Threadwood Studio",
    distance: 3.4,
    deliveryHours: 4,
    stock: 35,
    featured: false,
    trending: false,
    tags: ["Jewelry", "Accessories"],
    description: "Minimalist 4mm solid 925 sterling silver band ring, hand-polished with a brilliant high-shine reflective finish.",
    imagePrompt: "Minimalist thick solid sterling silver band ring, high reflective metallic sheen, centered on elegant light cream stone background, macro lens"
  },

  /* ═══════════════ GROCERIES (15) ═══════════════ */
  {
    id: "groc-1",
    name: "Organic Honeycrisp Apples",
    price: 240,
    originalPrice: 290,
    image: img("photo-1560806887-1e4cd0b6cbd6"),
    category: "groceries",
    rating: 4.8,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 50,
    featured: true,
    trending: true,
    tags: ["Fresh", "Organic"],
    description: "Sweet, crisp and incredibly juicy organic Honeycrisp apples freshly harvested from local valley orchards.",
    imagePrompt: "A stack of three glossy red Honeycrisp apples with tiny water droplets, sitting on clean white grocery catalog background, premium lighting"
  },
  {
    id: "groc-2",
    name: "Grass-Fed Organic Milk",
    price: 90,
    originalPrice: 110,
    image: img("photo-1563636619-e9143da7973b"),
    category: "groceries",
    rating: 4.9,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 30,
    featured: true,
    trending: true,
    tags: ["Dairy", "Fresh"],
    description: "Pure whole milk sourced from local family-owned pastures where cows graze on fresh green grass year-round.",
    imagePrompt: "Elegant glass milk bottle filled with rich whole white milk, resting on clean white studio grocery background with faint soft shadows"
  },
  {
    id: "groc-3",
    name: "Artisanal Sourdough Bread",
    price: 180,
    originalPrice: 220,
    image: img("photo-1509440159596-0249088772ff"),
    category: "groceries",
    rating: 4.9,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 12,
    featured: true,
    trending: true,
    tags: ["Bestseller", "Bakery"],
    description: "Locally baked crusty sourdough loaf made with organic stone-ground heritage wheat flour and natural wild yeast culture.",
    imagePrompt: "Golden-brown round crusty rustic sourdough loaf, dusted with flour, sliced in half showing airy crumb, centered on solid white background"
  },
  {
    id: "groc-4",
    name: "Pasture-Raised Brown Eggs",
    price: 110,
    originalPrice: 140,
    image: img("photo-1506976785307-8732e854ad03"),
    category: "groceries",
    rating: 4.8,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 25,
    featured: false,
    trending: true,
    tags: ["Fresh", "Organic"],
    description: "Dozen grade-A large brown farm eggs laid by free-range, pasture-raised hens fed a premium organic diet.",
    imagePrompt: "Open rustic recycled cardboard egg carton containing 12 uniform brown farm eggs, top-down shot isolated on white background"
  },
  {
    id: "groc-5",
    name: "Organic Basmati Rice",
    price: 499,
    originalPrice: 590,
    image: img("photo-1586201375761-83865001e31c"),
    category: "groceries",
    rating: 4.7,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 40,
    featured: false,
    trending: false,
    tags: ["Pantry", "Staple"],
    description: "Premium long-grain aged aromatic Basmati rice. Perfectly aged for fluffy texture and distinct nutty flavor.",
    imagePrompt: "A minimal textured jute bag overflowing with raw white long-grain Basmati rice, centered on absolute white background, commercial style"
  },
  {
    id: "groc-6",
    name: "Cold Pressed Olive Oil",
    price: 799,
    originalPrice: 950,
    image: img("photo-1474979266404-7eaacbcd87c5"),
    category: "groceries",
    rating: 4.8,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 20,
    featured: false,
    trending: true,
    tags: ["Pantry", "Cooking"],
    description: "Extra virgin cold-pressed olive oil sourced from single-estate olives, providing premium aroma and rich antioxidants.",
    imagePrompt: "Slim elegant dark green glass bottle of extra virgin olive oil, gold cap, isolated on clean pure white backdrop, studio lighting"
  },
  {
    id: "groc-7",
    name: "Organic Baby Spinach",
    price: 99,
    originalPrice: 120,
    image: img("photo-1576045057995-568f588f82fb"),
    category: "groceries",
    rating: 4.6,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 18,
    featured: false,
    trending: false,
    tags: ["Greens", "Fresh"],
    description: "Crisp and tender pre-washed organic baby spinach leaves, packed fresh in a breathable recyclable tray.",
    imagePrompt: "Clear recyclable plastic tray packed with vibrant green organic baby spinach leaves, isolated on white grocery photography backdrop"
  },
  {
    id: "groc-8",
    name: "Roasted Salted Almonds",
    price: 349,
    originalPrice: 420,
    image: img("photo-1596547609652-9cf5d8d76921"),
    category: "groceries",
    rating: 4.7,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 35,
    featured: false,
    trending: true,
    tags: ["Snacks", "Nuts"],
    description: "Slow-roasted Californian almonds dusted with pure sea salt. Perfect healthy snack packed with natural energy.",
    imagePrompt: "A white ceramic bowl filled with golden roasted almonds dusted with sea salt crystals, isolated on absolute white backdrop"
  },
  {
    id: "groc-9",
    name: "Cold Pressed Orange Juice",
    price: 149,
    originalPrice: 199,
    image: img("photo-1621506289937-a8e4df240d0b"),
    category: "groceries",
    rating: 4.5,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 22,
    featured: false,
    trending: false,
    tags: ["Juice", "Fresh"],
    description: "100% natural cold pressed orange juice. Never from concentrate, with no added sugars or artificial preservatives.",
    imagePrompt: "Clear glass bottle filled with bright vibrant pulpy orange juice, orange wedge resting beside it on white studio catalog background"
  },
  {
    id: "groc-10",
    name: "Premium Fresh Fruit Basket",
    price: 899,
    originalPrice: 1199,
    image: img("photo-1619546813926-a78fa6372cd2"),
    category: "groceries",
    rating: 4.9,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 3,
    stock: 15,
    featured: true,
    trending: false,
    tags: ["Gift", "Fresh"],
    description: "A gorgeous curated wooden basket filled with hand-selected seasonal local fruits like apples, oranges, grapes, and pears.",
    imagePrompt: "Woven wooden gift basket loaded with fresh colorful seasonal fruits, isolated on clean studio white background, premium photography"
  },
  {
    id: "groc-11",
    name: "Organic Green Tea Powder",
    price: 299,
    originalPrice: 399,
    image: img("photo-1536256263959-770b48d82b0a"),
    category: "groceries",
    rating: 4.6,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 28,
    featured: false,
    trending: false,
    tags: ["Tea", "Wellness"],
    description: "Premium stone-ground organic green tea powder sourced from high-altitude shade-grown local tea estates.",
    imagePrompt: "Small textured black ceramic bowl holding bright green powdered matcha tea, on clean studio backdrop, soft lighting"
  },
  {
    id: "groc-12",
    name: "Whole Bean Dark Coffee",
    price: 449,
    originalPrice: 549,
    image: img("photo-1447933601403-0c6688de566e"),
    category: "groceries",
    rating: 4.8,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 24,
    featured: false,
    trending: true,
    tags: ["Coffee", "Pantry"],
    description: "Rich dark roast coffee whole beans with warm notes of dark chocolate, cocoa, and caramelized toasted nuts.",
    imagePrompt: "Matte black modern coffee pouch packaging, coffee beans scattered around base, centered on white background, premium packaging render"
  },
  {
    id: "groc-13",
    name: "Organic Greek Yogurt",
    price: 120,
    originalPrice: 150,
    image: img("photo-1488477181946-6428a0291777"),
    category: "groceries",
    rating: 4.7,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 32,
    featured: false,
    trending: false,
    tags: ["Dairy", "Healthy"],
    description: "Thick, creamy and highly nutritious organic Greek plain yogurt packed with gut-healthy active live cultures.",
    imagePrompt: "Elegant glass jar filled with thick white greek yogurt, fresh blueberries resting on top, isolated on clean white backdrop"
  },
  {
    id: "groc-14",
    name: "Premium Mix Dry Fruits Box",
    price: 699,
    originalPrice: 850,
    image: img("photo-1596547609652-9cf5d8d76921"),
    category: "groceries",
    rating: 4.8,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 16,
    featured: false,
    trending: false,
    tags: ["Gift", "Pantry"],
    description: "Curated gift box containing high-grade almonds, cashews, pistachios, and dried sweet cranberries.",
    imagePrompt: "Elegant compartmentalized wooden gift box showcasing assorted dry fruits and nuts, centered on studio white background"
  },
  {
    id: "groc-15",
    name: "Indian Spices Gift Set",
    price: 490,
    originalPrice: 590,
    image: img("photo-1596040033229-a9821ebd058d"),
    category: "groceries",
    rating: 4.7,
    storeId: "s1",
    storeName: "Green Basket Mart",
    distance: 1.2,
    deliveryHours: 2,
    stock: 20,
    featured: false,
    trending: false,
    tags: ["Spices", "Pantry"],
    description: "A traditional wooden masala box including fresh cloves, cardamoms, cinnamon, turmeric, and high-grade saffron.",
    imagePrompt: "Premium wooden spice box holding assorted colorful Indian spices, top-down shot, isolated on solid white backdrop"
  },

  /* ═══════════════ BEAUTY (15) ═══════════════ */
  {
    id: "beau-1",
    name: "Botanical Face Serum",
    price: 1499,
    originalPrice: 1999,
    image: img("photo-1608248597279-f99d160bfcbc"),
    category: "beauty",
    rating: 4.9,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 18,
    featured: true,
    trending: true,
    tags: ["New", "Skincare"],
    description: "Luxury beauty face serum bottle in frosted amber glass with gold dropper, centered on a soft white background.",
    imagePrompt: "Luxury beauty face serum bottle in frosted amber glass with gold dropper, centered on a soft white background, studio lighting, professional cosmetic product photography, highly realistic, minimal aesthetic"
  },
  {
    id: "beau-2",
    name: "Velvet Matte Red Lipstick",
    price: 899,
    originalPrice: 1299,
    image: img("photo-1586495777744-4413f21062fa"),
    category: "beauty",
    rating: 4.7,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 35,
    featured: true,
    trending: true,
    tags: ["Matte", "Cosmetics"],
    description: "Highly pigmented velvet matte finish lipstick featuring an ultra-hydrating jojoba oil formula and rich classic crimson red color.",
    imagePrompt: "Elegant matte black lipstick tube uncapped showing deep crimson red velvet lipstick tip, isolated on white cosmetics catalog backdrop"
  },
  {
    id: "beau-3",
    name: "Hydrating Moisturizer Cream",
    price: 1299,
    originalPrice: 1699,
    image: img("photo-1601049541289-9b1b7bbbfe19"),
    category: "beauty",
    rating: 4.8,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 22,
    featured: true,
    trending: true,
    tags: ["Bestseller", "Skincare"],
    description: "Daily face cream formulated with hyaluronic acid and green tea extract for locking in multi-depth skin hydration.",
    imagePrompt: "Frosted glass luxury moisturizer jar with white lid, white cream visible inside, centered on clean studio light gray backdrop"
  },
  {
    id: "beau-4",
    name: "Argan Oil Nourishing Shampoo",
    price: 799,
    originalPrice: 999,
    image: img("photo-1535585209827-a15fcdbc4c2d"),
    category: "beauty",
    rating: 4.6,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 2,
    stock: 25,
    featured: false,
    trending: false,
    tags: ["Haircare", "Nourish"],
    description: "Sulfate-free hydrating shampoo enriched with pure organic Moroccan argan oil for dry, damaged or color-treated hair.",
    imagePrompt: "Elegant white shampoo pump dispenser bottle, minimalist label, warm studio lighting on white background, natural cosmetics catalog style"
  },
  {
    id: "beau-5",
    name: "Parisian Eau de Parfum",
    price: 3499,
    originalPrice: 4299,
    image: img("photo-1541643600914-78b084683601"),
    category: "beauty",
    rating: 4.9,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 10,
    featured: true,
    trending: true,
    tags: ["Luxury", "Fragrance"],
    description: "An elegant floral luxury perfume containing notes of French rose, jasmine grandiflorum, and light base of warm sandalwood.",
    imagePrompt: "Luxury crystal glass perfume spray bottle, gold detailing, showing light pink liquid inside, centered on clean minimalist marble studio slab"
  },
  {
    id: "beau-6",
    name: "Skin Renewal Night Cream",
    price: 1899,
    originalPrice: 2499,
    image: img("photo-1617897903246-719242758050"),
    category: "beauty",
    rating: 4.8,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 14,
    featured: false,
    trending: true,
    tags: ["Anti-Aging", "Skincare"],
    description: "Overnight recovery sleeping mask cream with retinol and peptides to promote active collagen synthesis and skin cell rejuvenation.",
    imagePrompt: "Premium navy blue glass cosmetic jar with silver screw cap, isolated on solid white studio backdrop, soft shadows"
  },
  {
    id: "beau-7",
    name: "12-Piece Makeup Brush Set",
    price: 1599,
    originalPrice: 2299,
    image: img("photo-1596462502278-27bfdc403348"),
    category: "beauty",
    rating: 4.7,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 20,
    featured: false,
    trending: false,
    tags: ["Accessories", "Makeup"],
    description: "Premium synthetic bristles professional makeup brushes set with vegan wooden handles and an elegant leather roll-up travel case.",
    imagePrompt: "Professional cosmetic makeup brush set fanned out neatly on clean white catalog background, realistic lighting"
  },
  {
    id: "beau-8",
    name: "Ultra-Sheer Sunscreen SPF 50",
    price: 699,
    originalPrice: 899,
    image: img("photo-1598440947619-2c35fc9aa908"),
    category: "beauty",
    rating: 4.6,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 45,
    featured: false,
    trending: true,
    tags: ["SPF", "Skincare"],
    description: "Lightweight, non-greasy mineral active sunscreen broad spectrum SPF 50 that leaves an invisible matte finish.",
    imagePrompt: "Sleek modern white tube of facial sunscreen, clean orange accent text, isolated on bright white background"
  },
  {
    id: "beau-9",
    name: "Rosemary Active Hair Serum",
    price: 1199,
    originalPrice: 1599,
    image: img("photo-1611080626919-7cf5a9dbab5b"),
    category: "beauty",
    rating: 4.7,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 30,
    featured: false,
    trending: false,
    tags: ["Haircare", "Growth"],
    description: "Advanced hair follicle strengthening oil serum containing rosemary extracts, biotin, and pure castor oil for thick volume.",
    imagePrompt: "Luxury small dark dropper bottle of hair oil, fresh rosemary sprigs resting nearby on white marble cosmetics backdrop"
  },
  {
    id: "beau-10",
    name: "Foaming Facial Cleanser",
    price: 599,
    originalPrice: 799,
    image: img("photo-1556228578-8c89e6adf883"),
    category: "beauty",
    rating: 4.5,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 40,
    featured: false,
    trending: false,
    tags: ["Cleanser", "Skincare"],
    description: "pH-balanced gentle foaming face wash containing organic chamomile extracts and pure skin-soothing aloe vera.",
    imagePrompt: "Clear glass pump bottle of liquid face wash with fine white foam visible inside, on white background with soft warm shadows"
  },
  {
    id: "beau-11",
    name: "Gel Shine Nail Polish Set",
    price: 499,
    originalPrice: 699,
    image: img("photo-1522337360788-8b13dee7a37e"),
    category: "beauty",
    rating: 4.4,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 50,
    featured: false,
    trending: false,
    tags: ["Nails", "Grooming"],
    description: "Durable high-gloss gel finish nail polish. Chip-resistant vegan formula that requires no UV lamps to dry.",
    imagePrompt: "Three modern small round glass nail polish bottles in pastel pink, nude and mauve shades, resting on absolute white studio background"
  },
  {
    id: "beau-12",
    name: "Shea Butter Body Lotion",
    price: 899,
    originalPrice: 1199,
    image: img("photo-1616683693504-3ea7e9ad6fec"),
    category: "beauty",
    rating: 4.7,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 24,
    featured: false,
    trending: true,
    tags: ["Moisturizer", "Body"],
    description: "Ultra-nourishing organic body lotion infused with unrefined African shea butter and sweet cold-pressed almond oil.",
    imagePrompt: "Large elegant body lotion pump container in minimal aesthetic beige, isolated on white studio backdrop with soft shadows"
  },
  {
    id: "beau-13",
    name: "Liquid Radiant Foundation",
    price: 1799,
    originalPrice: 2499,
    image: img("photo-1512496015851-a90fb38ba796"),
    category: "beauty",
    rating: 4.8,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 15,
    featured: false,
    trending: false,
    tags: ["Makeup", "Face"],
    description: "Buildable medium-coverage foundation that leaves a naturally dewy, glowing radiant finish. Available in 12 shades.",
    imagePrompt: "Premium frosted glass bottle of liquid makeup foundation with black pump, centered on absolute white cosmetics backdrop"
  },
  {
    id: "beau-14",
    name: "Plumping Peptide Lip Gloss",
    price: 649,
    originalPrice: 899,
    image: img("photo-1625093742435-6fa192b6fb10"),
    category: "beauty",
    rating: 4.6,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 1,
    stock: 35,
    featured: false,
    trending: true,
    tags: ["Gloss", "Lips"],
    description: "Nourishing peptide lip gloss that delivers instant volumetric plumping and deep, long-lasting glossy glass finish.",
    imagePrompt: "Transparent luxury lip gloss tube showing rose pink gloss inside, elegant metallic silver cap, isolated on white background"
  },
  {
    id: "beau-15",
    name: "Luxury Cosmetics Travel Kit",
    price: 2499,
    originalPrice: 3499,
    image: img("photo-1487412720507-e7ab37603c6f"),
    category: "beauty",
    rating: 4.9,
    storeId: "s4",
    storeName: "Bloom & Bath",
    distance: 0.8,
    deliveryHours: 2,
    stock: 8,
    featured: true,
    trending: false,
    tags: ["Luxury", "Gift"],
    description: "Elegant quilted leather cosmetics pouch containing travel sizes of cleanser, serum, moisturizer, and lip balm.",
    imagePrompt: "Quilted leather cream-colored designer makeup travel bag open with clean luxury cosmetic bottles visible, on white studio backdrop"
  },

  /* ═══════════════ HOME & LIVING (15) ═══════════════ */
  {
    id: "home-1",
    name: "Premium Fabric 3-Seater Sofa",
    price: 29999,
    originalPrice: 38000,
    image: img("photo-1555041469-a586c61ea9bc"),
    category: "home",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 4,
    stock: 5,
    featured: true,
    trending: true,
    tags: ["Furniture", "Living"],
    description: "Mid-century modern three-seater sofa upholstered in highly durable textured linen fabric with solid oak tapered legs.",
    imagePrompt: "Modern light gray fabric three-seater sofa, minimalist Scandinavian design, isolated on clean pure white studio background"
  },
  {
    id: "home-2",
    name: "Nordic Minimalist Table Lamp",
    price: 1899,
    originalPrice: 2799,
    image: img("photo-1507473885765-e6ed057f782c"),
    category: "home",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 20,
    featured: true,
    trending: true,
    tags: ["Lighting", "Minimalist"],
    description: "Elegant desk or bedside table lamp featuring a solid wooden base, matte white metal funnel shade and fabric power cord.",
    imagePrompt: "Minimalist desk table lamp with natural wooden base and matte white metal shade, illuminated, standing on clean white backdrop"
  },
  {
    id: "home-3",
    name: "Brushed Brass Wall Clock",
    price: 1499,
    originalPrice: 1999,
    image: img("photo-1509198397868-475647b2a1e5"),
    category: "home",
    rating: 4.6,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 15,
    featured: false,
    trending: true,
    tags: ["Decor", "Accessory"],
    description: "Minimalist silent non-ticking 12-inch metal wall clock featuring a brushed gold brass finish frame and modern hands.",
    imagePrompt: "Minimalist round wall clock, brushed gold brass finish outer ring, clean white dial with no numbers, isolated on plain white backdrop"
  },
  {
    id: "home-4",
    name: "Solid Oak Dining Table",
    price: 24999,
    originalPrice: 32000,
    image: img("photo-1577140917170-285929fb55b7"),
    category: "home",
    rating: 4.9,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 4,
    stock: 3,
    featured: true,
    trending: false,
    tags: ["Premium", "Furniture"],
    description: "Beautiful clean-lined 6-seater dining table handcrafted from solid European white oak wood, treated with protective natural oil.",
    imagePrompt: "Refined 6-seater rectangular dining table made of light natural oak wood, minimalist design, centered on solid white backdrop"
  },
  {
    id: "home-5",
    name: "Linen Semi-Sheer Curtains",
    price: 2299,
    originalPrice: 3299,
    image: img("photo-1513694203232-719a280e022f"),
    category: "home",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 4,
    stock: 12,
    featured: false,
    trending: false,
    tags: ["Window", "Textile"],
    description: "Breathable textured organic linen semi-sheer curtain pair. Designed to filter natural light beautifully into any bedroom or lounge.",
    imagePrompt: "Elegant long light beige linen textured curtains draped neatly over natural light source, clean white background catalog shot"
  },
  {
    id: "home-6",
    name: "Egyptian Cotton Bed Sheets",
    price: 3499,
    originalPrice: 4599,
    image: img("photo-1522771739844-6a9f6d5f14af"),
    category: "home",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 18,
    featured: false,
    trending: true,
    tags: ["Bedding", "Luxury"],
    description: "Authentic 600 thread count long-staple Egyptian cotton king size sheets set, offering an ultra-soft silky sateen finish.",
    imagePrompt: "Neatly folded luxury bed sheet set in slate gray sateen cotton, resting on absolute white background, catalog photography"
  },
  {
    id: "home-7",
    name: "Potted Monstera Deliciosa",
    price: 1299,
    originalPrice: 1799,
    image: img("photo-1614594975525-e45190c55d0b"),
    category: "home",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 25,
    featured: true,
    trending: true,
    tags: ["Plants", "Fresh"],
    description: "Iconic swiss cheese tropical houseplant Monstera Deliciosa, planted in a handmade rustic terracotta ceramic drainage pot.",
    imagePrompt: "Healthy indoor Monstera Deliciosa houseplant in handcrafted terracotta pot, centered on bright clean white backdrop"
  },
  {
    id: "home-8",
    name: "Smart Multi-Color LED Bulb",
    price: 899,
    originalPrice: 1499,
    image: img("photo-1550537687-c91072c4792d"),
    category: "home",
    rating: 4.4,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 50,
    featured: false,
    trending: false,
    tags: ["Smart", "Lighting"],
    description: "App and voice controlled smart LED light bulb supporting 16 million colors, schedule timers, and home automation sync.",
    imagePrompt: "Sleek smart LED light bulb glowing in soft warm amber light, isolated on white background, tech interior accessory"
  },
  {
    id: "home-9",
    name: "Hand-woven Wool Area Carpet",
    price: 6499,
    originalPrice: 8999,
    image: img("photo-1600121848594-d8644e57abab"),
    category: "home",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 4,
    stock: 6,
    featured: false,
    trending: false,
    tags: ["Rug", "Premium"],
    description: "Thick, soft hand-knotted natural wool area rug featuring a modern neutral cream Moroccan geometric trellis pattern.",
    imagePrompt: "Handwoven wool geometric pattern cream rug, flat lay overview angle, on white studio floor background"
  },
  {
    id: "home-10",
    name: "Nordic Wood Coffee Table",
    price: 4999,
    originalPrice: 6999,
    image: img("photo-1533090161767-e6ffed986c88"),
    category: "home",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 4,
    stock: 8,
    featured: false,
    trending: true,
    tags: ["Furniture", "Living"],
    description: "Minimalist kidney-shaped nesting coffee table crafted from solid ash wood veneer with three sturdy flared legs.",
    imagePrompt: "Minimalist nesting coffee table, natural light ash wood, three legs, set centered on studio white background"
  },
  {
    id: "home-11",
    name: "Ceramic Table Vase Set",
    price: 1199,
    originalPrice: 1799,
    image: img("photo-1612196808214-b8e1d6145a8c"),
    category: "home",
    rating: 4.6,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 22,
    featured: false,
    trending: false,
    tags: ["Decor", "Vase"],
    description: "Set of three textured ceramic tabletop flower vases, finished in earthy matte natural clay glazes for rustic shelf styling.",
    imagePrompt: "Trio of modern textured white and beige matte ceramic flower vases, clustered centered on plain white studio background"
  },
  {
    id: "home-12",
    name: "Ergonomic Office Chair",
    price: 8999,
    originalPrice: 12999,
    image: img("photo-1580481072645-022f9a6dbf27"),
    category: "home",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 10,
    featured: true,
    trending: true,
    tags: ["Office", "Comfort"],
    description: "High-back office mesh chair featuring customizable lumbar support, adjustable 3D armrests, and pneumatic seat height lift.",
    imagePrompt: "Ergonomic black mesh high-back office executive desk chair, centered on clean studio white background, premium render"
  },
  {
    id: "home-13",
    name: "10-Piece Copper Cookware Set",
    price: 7499,
    originalPrice: 9999,
    image: img("photo-1584269600464-37b1b58a9fe7"),
    category: "home",
    rating: 4.9,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 4,
    stock: 4,
    featured: true,
    trending: false,
    tags: ["Kitchen", "Cookware"],
    description: "Professional non-stick copper pots and pans cookware set with stainless steel handles and tempered glass steam-vent lids.",
    imagePrompt: "10-piece professional copper cookware set consisting of pots, pans and lids, arranged neatly on white catalog photography backdrop"
  },
  {
    id: "home-14",
    name: "Solid Wood Storage Cabinet",
    price: 14999,
    originalPrice: 18900,
    image: img("photo-1595428774223-ef52624120d2"),
    category: "home",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 4,
    stock: 3,
    featured: false,
    trending: false,
    tags: ["Furniture", "Storage"],
    description: "Spacious storage cabinet dresser containing adjustable shelving, carved slatted slide-doors, made from solid rubberwood.",
    imagePrompt: "Warm rubberwood low profile storage sideboard console cabinet, centered on plain white studio backdrop, soft natural shadows"
  },
  {
    id: "home-15",
    name: "Geometric Gold Wall Decor",
    price: 1799,
    originalPrice: 2499,
    image: img("photo-1540932239986-30128078f3c5"),
    category: "home",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 15,
    featured: false,
    trending: false,
    tags: ["Decor", "Wall"],
    description: "Sleek 3D geometric abstract metal wall hanging sculpture, finished in an elegant hand-painted brushed gold powder coat.",
    imagePrompt: "3D abstract gold metal geometric line wall sculpture art, isolated hanging on solid white backdrop, clean photography"
  },

  /* ═══════════════ SPORTS (15) ═══════════════ */
  {
    id: "spor-1",
    name: "Match Leather Football",
    price: 1299,
    originalPrice: 1999,
    image: img("photo-1518063319789-7217e6706b04"),
    category: "sports",
    rating: 4.6,
    storeId: "s5",
    storeName: "Hearth & Home", // mapped store
    distance: 4.0,
    deliveryHours: 2,
    stock: 25,
    featured: false,
    trending: true,
    tags: ["Soccer", "Match"],
    description: "Professional match-grade size 5 leather football constructed with thermally bonded textured panels for stable trajectory.",
    imagePrompt: "Premium black and white classic leather football, standing upright on clean white studio background with soft natural shadows"
  },
  {
    id: "spor-2",
    name: "English Willow Cricket Bat",
    price: 4500,
    originalPrice: 6500,
    image: img("photo-1531415074968-036ba1b575da"),
    category: "sports",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 12,
    featured: true,
    trending: true,
    tags: ["Cricket", "Willow"],
    description: "Grade-1 English willow cricket bat, professionally pressed with a massive sweet spot, thick edges, and high rubber grip.",
    imagePrompt: "Handcrafted English willow cricket bat showing clean wood grain, standing angled on a solid pure white photography background"
  },
  {
    id: "spor-3",
    name: "Hex Iron Dumbbells (10kg Pair)",
    price: 2499,
    originalPrice: 3499,
    image: img("photo-1517838277536-f5f99be501cd"),
    category: "sports",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 15,
    featured: true,
    trending: true,
    tags: ["Fitness", "Gym"],
    description: "Pair of 10kg heavy hex dumbbells featuring anti-roll solid cast iron core heads coated in premium low-odor black rubber.",
    imagePrompt: "Pair of heavy black rubber encased hex dumbbells, chrome knurled handles, isolated on plain white photography background"
  },
  {
    id: "spor-4",
    name: "Non-Slip Rubber Yoga Mat",
    price: 1199,
    originalPrice: 1799,
    image: img("photo-1592432678016-e910b452f9a2"),
    category: "sports",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 35,
    featured: false,
    trending: false,
    tags: ["Yoga", "Wellness"],
    description: "6mm thick, high-density natural tree rubber yoga mat offering elite slip-resistance and double-sided textured cushion.",
    imagePrompt: "Neatly rolled up dusty pink organic natural rubber yoga mat, centered on absolute white studio backdrop, soft lighting"
  },
  {
    id: "spor-5",
    name: "Lightweight Running Shoes",
    price: 3499,
    originalPrice: 4999,
    image: img("photo-1476480862126-209bfaa8edc8"),
    category: "sports",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 16,
    featured: true,
    trending: true,
    tags: ["Bestseller", "Footwear"],
    description: "High-performance mesh upper marathon running shoes featuring an ultra-responsive responsive foam cushion midsole.",
    imagePrompt: "Lightweight neon green athletic running shoe, side view, floating centered on clean white backdrop, professional sports catalog style"
  },
  {
    id: "spor-6",
    name: "Official Indoor Basketball",
    price: 1899,
    originalPrice: 2499,
    image: img("photo-1546519638-68e109498ffc"),
    category: "sports",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 20,
    featured: false,
    trending: true,
    tags: ["Basketball", "Indoor"],
    description: "Official size 7 basketball constructed with composite micro-fiber leather cover for superior grip control.",
    imagePrompt: "Classic textured orange composite leather basketball standing centered on clear white studio backdrop, soft shadows"
  },
  {
    id: "spor-7",
    name: "Vacuum Insulated Sports Bottle",
    price: 899,
    originalPrice: 1299,
    image: img("photo-1602143407151-7111542de6e8"),
    category: "sports",
    rating: 4.6,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 45,
    featured: false,
    trending: false,
    tags: ["Hydrate", "Bottle"],
    description: "Double-walled copper vacuum insulated food-grade stainless steel bottle. Keeps drinks cold for 24h or hot for 12h.",
    imagePrompt: "Matte black stainless steel double-wall vacuum insulated sports water bottle, isolated on bright white background"
  },
  {
    id: "spor-8",
    name: "Smart Active Fitness Band",
    price: 2499,
    originalPrice: 3499,
    image: img("photo-1575311373937-040b8e1fd5b6"),
    category: "sports",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 28,
    featured: false,
    trending: false,
    tags: ["Smart", "Tracker"],
    description: "Ultra-lightweight activity wristband tracking blood oxygen levels, heart-rate, step logs, sleep stats and workout modes.",
    imagePrompt: "Sleek fitness activity tracker band with digital screen displaying steps metric, isolated centered on white backdrop"
  },
  {
    id: "spor-9",
    name: "Anti-Burst Gym Yoga Ball",
    price: 799,
    originalPrice: 1199,
    image: img("photo-1518611012118-696072aa579a"),
    category: "sports",
    rating: 4.4,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 30,
    featured: false,
    trending: false,
    tags: ["Gym", "Stability"],
    description: "Professional 65cm anti-burst stability fitness exercise ball, ideal for core training, pregnancy yoga and posture balance.",
    imagePrompt: "A charcoal gray textured anti-burst gym exercise stability ball, centered on solid white photography background"
  },
  {
    id: "spor-10",
    name: "Carbon Fiber Tennis Racket",
    price: 3899,
    originalPrice: 4999,
    image: img("photo-1560012057-4372e14c5085"),
    category: "sports",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 14,
    featured: false,
    trending: true,
    tags: ["Tennis", "Racket"],
    description: "Lightweight carbon fiber tennis racket with vibration dampening technology, pre-strung with high-tension nylon strings.",
    imagePrompt: "Carbon fiber sleek gray tennis racket with white grip tape, neon yellow tennis ball resting beside it on white background"
  },
  {
    id: "spor-11",
    name: "Breathable Leather Gym Gloves",
    price: 599,
    originalPrice: 899,
    image: img("photo-1599058917212-d750089bc07e"),
    category: "sports",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 40,
    featured: false,
    trending: false,
    tags: ["Gym", "Gloves"],
    description: "Full-grain leather gym lifting gloves featuring padded palm buffers, wrist wraps, and breathable mesh backing.",
    imagePrompt: "Pair of leather weightlifting gloves, padded palms, laid flat on pure white studio catalog background"
  },
  {
    id: "spor-12",
    name: "Compact Folding Treadmill",
    price: 24999,
    originalPrice: 32000,
    image: img("photo-1571019613454-1cb2f99b2d8b"),
    category: "sports",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 4,
    stock: 4,
    featured: true,
    trending: false,
    tags: ["Treadmill", "Premium"],
    description: "Under-desk quiet smart folding treadmill motor supporting speeds up to 12km/h and LED touch tracking screen panel.",
    imagePrompt: "Compact folding under-desk walking treadmill machine in sleek black alloys, isolated on solid white backdrop"
  },
  {
    id: "spor-13",
    name: "Weighted Speed Skipping Rope",
    price: 499,
    originalPrice: 799,
    image: img("photo-1434608519344-49d77a699e1d"),
    category: "sports",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 50,
    featured: false,
    trending: false,
    tags: ["Workout", "Rope"],
    description: "High-speed adjustable steel wire skipping jump rope with dual-ball bearing handles for high-speed workouts.",
    imagePrompt: "Black steel-wire jump skipping speed rope coiled neatly, red aluminum alloy handles, on white studio backdrop"
  },
  {
    id: "spor-14",
    name: "Aero-Shield Cycling Helmet",
    price: 1799,
    originalPrice: 2499,
    image: img("photo-1596131397999-9d954e7d0130"),
    category: "sports",
    rating: 4.6,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 18,
    featured: false,
    trending: false,
    tags: ["Cycling", "Safety"],
    description: "Lightweight aerodynamic bike safety helmet featuring 22 strategic cooling wind vents, adjustable dial, and tail safety LED light.",
    imagePrompt: "Aerodynamic matte white and black road cycling helmet, isolated centered on clean white backdrop, sports product photography"
  },
  {
    id: "spor-15",
    name: "Heavy Duty Gym Sports Bag",
    price: 1499,
    originalPrice: 2199,
    image: img("photo-1553062407-98eeb64c6a62"),
    category: "sports",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 22,
    featured: false,
    trending: true,
    tags: ["Gym", "Bags"],
    description: "Waterproof gym duffel travel bag equipped with dedicated ventilated shoe compartment and padded shoulder straps.",
    imagePrompt: "Heavy-duty gray nylon athletic duffel gym bag, empty stand-up display, isolated on clean white photography backdrop"
  },

  /* ═══════════════ BOOKS (15) ═══════════════ */
  {
    id: "book-1",
    name: "Mindset Dynamics",
    price: 399,
    originalPrice: 499,
    image: img("photo-1544716278-ca5e3f4abd8c"),
    category: "books",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 30,
    featured: true,
    trending: true,
    tags: ["Self-Help", "Growth"],
    description: "Unlocking limits of cognitive performance and habit loops. Written by acclaimed cognitive psychologist Dr. Robert Harris.",
    imagePrompt: "Self-help book titled Mindset Dynamics with minimalistic green cover design, resting on white studio catalog background"
  },
  {
    id: "book-2",
    name: "Scale up Strategies",
    price: 450,
    originalPrice: 599,
    image: img("photo-1589829085413-56de8ae18c73"),
    category: "books",
    rating: 4.9,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 15,
    featured: true,
    trending: true,
    tags: ["Startup", "Finance"],
    description: "Comprehensive startup expansion playbook on building, seed funding, scaling, and exiting modern web businesses.",
    imagePrompt: "A business book titled Scale up Strategies with gold foil lettering on matte black cover, isolated on solid white studio background"
  },
  {
    id: "book-3",
    name: "Mastering TypeScript",
    price: 899,
    originalPrice: 1199,
    image: img("photo-1629654297299-c8506221ca97"),
    category: "books",
    rating: 4.9,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 12,
    featured: true,
    trending: true,
    tags: ["Bestseller", "Tech"],
    description: "Deep dive reference manual covering type validation systems, abstract factories, decorator architectures and build configs.",
    imagePrompt: "Programming textbook titled Mastering TypeScript with minimal abstract geometric blue cover, on white backdrop"
  },
  {
    id: "book-4",
    name: "The Nebula Odyssey",
    price: 349,
    originalPrice: 450,
    image: img("photo-1543002588-bfa74002ed7e"),
    category: "books",
    rating: 4.6,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 22,
    featured: false,
    trending: false,
    tags: ["Novels", "Sci-Fi"],
    description: "An epic sci-fi space exploration odyssey through stellar deep galaxies, black holes, and advanced human space civilizations.",
    imagePrompt: "Science fiction novel cover showing beautiful galactic painting, titled The Nebula Odyssey, clean book catalog shot"
  },
  {
    id: "book-5",
    name: "Atomic Habits Tracker",
    price: 299,
    originalPrice: 399,
    image: img("photo-1531346878377-a5be20888e57"),
    category: "books",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 40,
    featured: false,
    trending: true,
    tags: ["Productivity", "Habits"],
    description: "Structured daily tracking notebook designed to log progressive lifestyle loops, micro goals and healthy wellness habits.",
    imagePrompt: "Minimalist grid pattern thick productivity notebook journal, lying open on clean white studio backdrop"
  },
  {
    id: "book-6",
    name: "Design Systems Blueprint",
    price: 799,
    originalPrice: 999,
    image: img("photo-1512820790803-83ca734da794"),
    category: "books",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 10,
    featured: false,
    trending: true,
    tags: ["Design", "UX-UI"],
    description: "Professional blueprint for building scalable UI components, layout tokens and design systems in React and Tailwind CSS.",
    imagePrompt: "Thick book titled Design Systems Blueprint with bright yellow abstract geometric cover, clean white background, studio shot"
  },
  {
    id: "book-7",
    name: "AI & Neural Architectures",
    price: 999,
    originalPrice: 1399,
    image: img("photo-1506880018603-83d5b814b5a6"),
    category: "books",
    rating: 4.9,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 8,
    featured: true,
    trending: false,
    tags: ["Tech", "AI"],
    description: "Comprehensive guide to deep learning neural networks, natural language processing models and algorithmic intelligence.",
    imagePrompt: "Heavy reference book titled AI and Neural Architectures, silver metallic text, centered on pure white studio background"
  },
  {
    id: "book-8",
    name: "Capital Investments 101",
    price: 499,
    originalPrice: 650,
    image: img("photo-1592492159418-acd9f5afb5ba"),
    category: "books",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 18,
    featured: false,
    trending: false,
    tags: ["Finance", "Investing"],
    description: "Introduction to corporate wealth building, stock analysis, compound interest systems, and real estate market investing.",
    imagePrompt: "Textbook titled Capital Investments 101, green textured leather cover, gold embossed text, isolated on solid white backdrop"
  },
  {
    id: "book-9",
    name: "Deep Work Tactics",
    price: 380,
    originalPrice: 480,
    image: img("photo-1497633762265-9d179a990aa6"),
    category: "books",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 25,
    featured: false,
    trending: true,
    tags: ["Productivity", "Focus"],
    description: "Practical rules and tactics for achieving intense cognitive focus, blocking distractions, and mastering complex skills quickly.",
    imagePrompt: "Paperback book titled Deep Work Tactics with bold red graphic cover design, flat lay on white studio background"
  },
  {
    id: "book-10",
    name: "The Psychology of Time",
    price: 420,
    originalPrice: 550,
    image: img("photo-1541963463532-d68292c34b19"),
    category: "books",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 14,
    featured: false,
    trending: false,
    tags: ["Psychology", "Studies"],
    description: "An analytical study exploring human time perception, neurological memory clocks, and chronological behavior loops.",
    imagePrompt: "A thick research book titled The Psychology of Time, cream hardback textured cover, isolated on plain white backdrop"
  },
  {
    id: "book-11",
    name: "Tokyo Neon (Modern Manga)",
    price: 599,
    originalPrice: 799,
    image: img("photo-1578632767115-351597cf2477"),
    category: "books",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 20,
    featured: false,
    trending: false,
    tags: ["Manga", "Graphic"],
    description: "Beautifully illustrated volume 1 modern cyberpunk graphical graphic novel following a futuristic runner in Tokyo.",
    imagePrompt: "Graphic novel manga titled Tokyo Neon with highly detailed colorful cyberpunk character illustration, book display on white background"
  },
  {
    id: "book-12",
    name: "A Shadow in the Rain",
    price: 299,
    originalPrice: 399,
    image: img("photo-1495640388908-05fa85288e61"),
    category: "books",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 35,
    featured: false,
    trending: false,
    tags: ["Novel", "Mystery"],
    description: "A fast-paced classic detective noir murder mystery thriller set in fog-drenched 1950s London alleyways.",
    imagePrompt: "Mystery novel book cover showing rain-soaked street shadow silhouettes, titled A Shadow in the Rain, isolated on white background"
  },
  {
    id: "book-13",
    name: "The Founder Mindset",
    price: 499,
    originalPrice: 650,
    image: img("photo-1544947950-fa07a98d237f"),
    category: "books",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 16,
    featured: false,
    trending: true,
    tags: ["Startup", "Business"],
    description: "Psychological resilience guide for tech startup founders managing team growth, scaling stress, and market pivots.",
    imagePrompt: "Startup guidebook titled The Founder Mindset, white hardback texture with blue abstract shapes, on white background"
  },
  {
    id: "book-14",
    name: "Modern Web Architecture",
    price: 849,
    originalPrice: 1099,
    image: img("photo-1516979187457-637abb4f9353"),
    category: "books",
    rating: 4.9,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 10,
    featured: false,
    trending: false,
    tags: ["Coding", "System"],
    description: "Design textbook covering RESTful APIs, distributed microservices, state sync layers, and high-load web deployment caching.",
    imagePrompt: "Computer science textbook titled Modern Web Architecture, abstract purple networking graphics on cover, book on white backdrop"
  },
  {
    id: "book-15",
    name: "Art of Clear Thinking",
    price: 360,
    originalPrice: 450,
    image: img("photo-1516962215378-7fa2e137ae93"),
    category: "books",
    rating: 4.6,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 22,
    featured: false,
    trending: false,
    tags: ["Psychology", "Focus"],
    description: "Unraveling mental cognitive bias to establish clear decision pathways and robust logical thinking habits.",
    imagePrompt: "Self-help book cover titled Art of Clear Thinking, minimalist pencil line drawing of head silhouette, isolated on white background"
  },

  /* ═══════════════ TOYS & GAMES (15) ═══════════════ */
  {
    id: "toys-1",
    name: "Velvet Plush Teddy Bear",
    price: 999,
    originalPrice: 1499,
    image: img("photo-1559251606-c623743a6d76"),
    category: "toys",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 30,
    featured: true,
    trending: true,
    tags: ["Plush", "Kids"],
    description: "Incredibly soft, huggable premium velvet golden-brown plush teddy bear with a classic red satin neck bow tie.",
    imagePrompt: "Adorable golden-brown premium plush teddy bear sitting upright wearing a red satin neck ribbon bow, centered on pure white backdrop"
  },
  {
    id: "toys-2",
    name: "High-Speed RC Drift Car",
    price: 2499,
    originalPrice: 3499,
    image: img("photo-1594787318286-3d835c1d207f"),
    category: "toys",
    rating: 4.6,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 18,
    featured: true,
    trending: true,
    tags: ["RC", "Toys"],
    description: "1:16 scale radio-controlled high-speed drift racing car with rechargeable battery, active shock absorbers, and functional LED headlights.",
    imagePrompt: "Bright red sleek high-speed RC drift crawler toy car, centered angling slightly, isolated on crisp white background, studio render"
  },
  {
    id: "toys-3",
    name: "LEGO Space Station Creator",
    price: 4999,
    originalPrice: 6499,
    image: img("photo-1560942485-b2a11cc13456"),
    category: "toys",
    rating: 4.9,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 10,
    featured: true,
    trending: true,
    tags: ["Bestseller", "Blocks"],
    description: "Build your own detailed orbital space station with astronauts models, modular scientific modules and solar panel sails.",
    imagePrompt: "Highly detailed plastic toy space station LEGO block build setup, centered on solid white catalog photography backdrop, studio light"
  },
  {
    id: "toys-4",
    name: "1000-Piece Landscape Puzzle",
    price: 699,
    originalPrice: 999,
    image: img("photo-1585320806297-9794b3e4eeae"),
    category: "toys",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 25,
    featured: false,
    trending: false,
    tags: ["Puzzle", "Games"],
    description: "Thick, precise-fit wooden jigsaw puzzle pieces forming a breathtaking vibrant alpine lake landscape painting upon completion.",
    imagePrompt: "Colorful puzzle cardboard box showing mountain lake scene, with a few loose jigsaw pieces resting beside it on white backdrop"
  },
  {
    id: "toys-5",
    name: "Weighted Wooden Chess Set",
    price: 1799,
    originalPrice: 2499,
    image: img("photo-1529699211952-734e80c4d42b"),
    category: "toys",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 12,
    featured: true,
    trending: false,
    tags: ["Chess", "Classic"],
    description: "Premium folding walnut wooden chess board with hand-carved weighted magnetic wooden chessmen pieces and soft storage slots.",
    imagePrompt: "Crafted dark walnut wood chess board set up with carved wooden figures, angled view, isolated on solid white background"
  },
  {
    id: "toys-6",
    name: "Classic Strategy Board Game",
    price: 1199,
    originalPrice: 1799,
    image: img("photo-1610890716171-6b1bb98ffd09"),
    category: "toys",
    rating: 4.6,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 20,
    featured: false,
    trending: true,
    tags: ["Board-Game", "Family"],
    description: "Immersive multiplayer resource collection and strategy tabletop board game for family nights and tactical gaming sessions.",
    imagePrompt: "Curated premium board game cardboard box showing creative historical illustrations, dice and tokens stacked on clean white backdrop"
  },
  {
    id: "toys-7",
    name: "Electric Classic Toy Train",
    price: 2299,
    originalPrice: 2999,
    image: img("photo-1546776310-eef45dd6d63c"),
    category: "toys",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 15,
    featured: false,
    trending: false,
    tags: ["Train", "Electric"],
    description: "Authentic steam locomotive model toy train set with passenger cars, cargo carriers, smoke effects, sound, and a customizable track loop.",
    imagePrompt: "Vintage battery-powered toy model train steam engine on plastic tracks, centered on pure white studio background"
  },
  {
    id: "toys-8",
    name: "Collector Edition Barbie Doll",
    price: 1499,
    originalPrice: 1999,
    image: img("photo-1558877385-81a1c7e67d72"),
    category: "toys",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 22,
    featured: false,
    trending: false,
    tags: ["Barbie", "Collector"],
    description: "Stunning fashion doll dressed in a detailed modern satin gala dress, complete with designer accessories and stand.",
    imagePrompt: "Collector doll in elegant modern pink tulle and satin dress, detailed accessories, standing centered on white backdrop"
  },
  {
    id: "toys-9",
    name: "Magnetic Building Blocks Set",
    price: 1899,
    originalPrice: 2499,
    image: img("photo-1587654780291-39c9404d746b"),
    category: "toys",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 35,
    featured: false,
    trending: true,
    tags: ["Magnetic", "Blocks"],
    description: "100-piece colorful geometric translucent magnetic building blocks set for fostering spatial skills and structural logic.",
    imagePrompt: "Colorful transparent magnetic building blocks arranged neatly to form toy castle, standing on absolute white backdrop"
  },
  {
    id: "toys-10",
    name: "Retro Handheld Game Console",
    price: 1299,
    originalPrice: 1899,
    image: img("photo-1531525645387-7f14be1bdbbd"),
    category: "toys",
    rating: 4.4,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 40,
    featured: false,
    trending: false,
    tags: ["Console", "Retro"],
    description: "Compact handheld retro console pre-loaded with 400 classical 8-bit arcade platformer games, featuring clear LCD display.",
    imagePrompt: "Retro yellow handheld digital game boy console, red action buttons, screen glowing, isolated centered on white backdrop"
  },
  {
    id: "toys-11",
    name: "STEM Solar Powered Robot",
    price: 1599,
    originalPrice: 2199,
    image: img("photo-1535378917042-10a22c95931a"),
    category: "toys",
    rating: 4.7,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 16,
    featured: false,
    trending: true,
    tags: ["STEM", "Educational"],
    description: "12-in-1 solar-powered educational robotics building kit, teaching clean energy and mechanics through fun manual construction.",
    imagePrompt: "Modern gray plastic solar panel toy crawler robot, centered on crisp white studio background, high quality catalog photo"
  },
  {
    id: "toys-12",
    name: "High-Speed Magnetic Rubik's",
    price: 499,
    originalPrice: 799,
    image: img("photo-1591389703635-e15a07b842d7"),
    category: "toys",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 50,
    featured: false,
    trending: false,
    tags: ["Rubik's", "Puzzle"],
    description: "Competition-grade speed Rubik's cube featuring a smart internal magnetic core for ultra-smooth corner-cutting and fast solving.",
    imagePrompt: "Modern 3x3 magnetic rubik's cube, premium matte surface, half-turned displaying vibrant red yellow blue facets, on white backdrop"
  },
  {
    id: "toys-13",
    name: "Kids Sporty Mountain Bike",
    price: 6499,
    originalPrice: 8999,
    image: img("photo-1485965120184-e220f721d03e"),
    category: "toys",
    rating: 4.8,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 3,
    stock: 6,
    featured: true,
    trending: false,
    tags: ["Bicycle", "Sports"],
    description: "Vibrant sporty mountain bicycle for kids featuring safe dual disc-brakes, solid auxiliary training wheels, and robust carbon steel frame.",
    imagePrompt: "Neon orange robust kids 16-inch mountain bicycle, rear training wheels attached, centered on pure white studio background"
  },
  {
    id: "toys-14",
    name: "Mini Altitude Hold Drone Toy",
    price: 1999,
    originalPrice: 2799,
    image: img("photo-1527977966376-1c8408f9f108"),
    category: "toys",
    rating: 4.6,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 20,
    featured: false,
    trending: true,
    tags: ["Drone", "RC"],
    description: "Kid-friendly safe pocket drone featuring durable full protective blade bumpers, altitude hold sensors, and one-key flips.",
    imagePrompt: "Mini round kid-friendly toy quadcopter drone in bright green, secure prop guards, isolated on absolute white backdrop"
  },
  {
    id: "toys-15",
    name: "Marvel Superhero Action Figure",
    price: 899,
    originalPrice: 1299,
    image: img("photo-1569003339405-ea396a5a8a90"),
    category: "toys",
    rating: 4.5,
    storeId: "s5",
    storeName: "Hearth & Home",
    distance: 4.0,
    deliveryHours: 2,
    stock: 30,
    featured: false,
    trending: false,
    tags: ["Action", "Hero"],
    description: "Highly articulated 12-inch superhero action figure featuring intricate armored molding design and detachable combat accessories.",
    imagePrompt: "Highly detailed sci-fi armored action figure toy with dynamic battle pose, isolated centered on solid white catalog backdrop"
  }
];

export const orders = [
  { id: "o1", date: "May 2, 2026", total: 1240, status: "Delivered", items: 3, store: "Green Basket Mart" },
  { id: "o2", date: "Apr 28, 2026", total: 8499, status: "Delivered", items: 1, store: "Volt Electronics" },
  { id: "o3", date: "Apr 14, 2026", total: 2698, status: "Delivered", items: 2, store: "Bloom & Bath" },
];

export const user = {
  name: "Aanya Sharma",
  email: "aanya@localmart.app",
  location: "Koramangala, Bengaluru",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
};
